* 352 cases: (dvAdaSa = 'twelve')
 There are 349 instances of dBAdaS, all changed to dvAdaS.
 The program logic changes these based on several criteria.
 275 are word initial db:
; 349 : "dbAdaS"  :::  275  '\bdb' => 'dv'
 The remaining 74 are changed just by the rule 'dbAdaS' => 'dvAdaS'
; 349 : "dbAdaS"  :::  74  'dbAdaS' => 'dvAdaS'
; 5 : "dbAda-"  :::  3  '\bdb' => 'dv'

* 315 cases: (dvitIya = 'second')
; 311 : "dbitIy"  :::  275  '\bdb' => 'dv'
; 311 : "dbitIy"  :::  36  'dbitIy' => 'dvitIy'
; 4 : "dbitI-"  :::  4  '\bdb' => 'dv'
* 234 cases: (yadvA = 'or else' (acc. to Macdonell))
(ending) dbA => dvA
; 303 : "dbA"  :::  234  '\byadbA(\b|$)' => 'yadvA'

* 124 cases: (dvandva = 'pair'),(dvandvin
; 266 : "d-MULTI"  :::  63  'dbandb' => 'dvandv'
;  30 : "dbandv"  :::  30  'dbandv' => 'dvandv'
;  12 : "dbaH"  :::  4  'dvandb' => 'dvandv'
;   6 : "dbaM"  :::  3  'dvandb' => 'dvandv'
;   3 : "dba"  :::  1  'dvandb' => 'dvandv'
; 3 : "dbatve"  :::  3  'dvandb' => 'dvandv'
; 3 : "dbayuk"  :::  3  'dvandb' => 'dvandv'
; 2 : "dbamit"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbajAn"  :::  1  'dvandb' => 'dvandv'
; 266 : "d-MULTI"  :::  1  'dvandb' => 'dvandv' , 'dbic' => 'dvic'
; 266 : "d-MULTI"  :::  2  'dbandb' => 'dvandv' , 'dvandb' => 'dvandv'
; 86 : "dbe"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbamut"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbaBAv"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbopAD"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbamay"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbo'pi"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbabal"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbamah"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbiviB"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbamAr"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbasya"  :::  1  'dvandb' => 'dvandv'
; 1 : "dbamev"  :::  1  'dvandb' => 'dvandv'
* 358 cases: (dvaya = 'pair', dvayat)
; 126 : "dbayam"  :::  20  '\bdb' => 'dv'
; 126 : "dbayam"  :::  106  'dbay(a|o|e|A)' => 'dvay\1'
; 90 : "dbayaM"  :::  13  '\bdb' => 'dv'
; 90 : "dbayaM"  :::  77  'dbay(a|o|e|A)' => 'dvay\1'
; 22 : "dbaye"  :::  1  '\bdb' => 'dv'
; 22 : "dbaye"  :::  21  'dbay(a|o|e|A)' => 'dvay\1'
; 20 : "dbayas"  :::  20  'dbay(a|o|e|A)' => 'dvay\1'
; 13 : "dbayoH"  :::  6  'dbay(a|o|e|A)' => 'dvay\1'
; 13 : "dbayoH"  :::  7  '\bdb' => 'dv'
; 12 : "dbayAt"  :::  2  '\bdb' => 'dv'
; 12 : "dbayAt"  :::  10  'dbay(a|o|e|A)' => 'dvay\1'
; 10 : "dbayay"  :::  2  '\bdb' => 'dv'
; 10 : "dbayay"  :::  8  'dbay(a|o|e|A)' => 'dvay\1'
; 9 : "dbayen"  :::  2  '\bdb' => 'dv'
; 9 : "dbayen"  :::  7  'dbay(a|o|e|A)' => 'dvay\1'
; 9 : "dbayaY"  :::  9  'dbay(a|o|e|A)' => 'dvay\1'
; 7 : "dbaya-"  :::  6  'dbay(a|o|e|A)' => 'dvay\1'
; 7 : "dbaya-"  :::  1  '\bdb' => 'dv'
; 6 : "dbayon"  :::  6  'dbay(a|o|e|A)' => 'dvay\1'
; 6 : "dbayap"  :::  6  'dbay(a|o|e|A)' => 'dvay\1'
; 5 : "dbayag"  :::  1  '\bdb' => 'dv'
; 5 : "dbayag"  :::  4  'dbay(a|o|e|A)' => 'dvay\1'
; 5 : "dbayav"  :::  5  'dbay(a|o|e|A)' => 'dvay\1'
; 4 : "dbayAD"  :::  4  'dbay(a|o|e|A)' => 'dvay\1'
; 4 : "dbayad"  :::  1  '\bdb' => 'dv'
; 4 : "dbayad"  :::  3  'dbay(a|o|e|A)' => 'dvay\1'
; 3 : "dbayo-"  :::  3  '\bdb' => 'dv'
; 3 : "dbayAB"  :::  3  'dbay(a|o|e|A)' => 'dvay\1'
; 3 : "dbayar"  :::  3  'dbay(a|o|e|A)' => 'dvay\1'
; 2 : "dbayaD"  :::  1  '\bdb' => 'dv'
; 2 : "dbayaD"  :::  1  'dbay(a|o|e|A)' => 'dvay\1'
; 2 : "dbayop"  :::  2  'dbay(a|o|e|A)' => 'dvay\1'
* 112 cases: (dviguRita 'doubled', dviguRa = 'twice')
; 112 : "dbiguR"  :::  102  '\bdb' => 'dv'
; 112 : "dbiguR"  :::  10  'dbiguR' => 'dviguR'
* 018 cases: (vAkya = 'speech')
; 266 : "d-MULTI"  :::  1  'dbAkya' => 'dvAkya' , 'dbrUhi' ok
; 17 : "dbAkya"  :::  1  '\bdb' => 'dv'
; 17 : "dbAkya"  :::  16  'dbAkya' => 'dvAkya'
* 506 cases: (dvi = 'two', dvO)
; 86 : "dbe"  :::  80  '\bdb' => 'dv'
; 65 : "dbO"  :::  62  '\bdb' => 'dv'
; 31 : "dbayor"  :::  26  '\bdb' => 'dv'
; 31 : "dbayor"  :::  5  'dbay(a|o|e|A)' => 'dvay\1'
; 30 : "dbAByA"  :::  29  '\bdb' => 'dv'
; 30 : "dbAByA"  :::  1  'dbAByA' => 'dvAByA'
; 11 : "dbicat"  :::  11  '\bdb' => 'dv'
; 10 : "dbisah"  :::  9  '\bdb' => 'dv'
; 10 : "dbisah"  :::  1  'dbisah' => 'dvisah'
; 10 : "dbijan"  :::  8  '\bdb' => 'dv'
; 9 : "dbiSat"  :::  7  '\bdb' => 'dv'
; 9 : "dbiSat"  :::  2  'dbiSat' => 'dviSat'
; 9 : "dbidal"  :::  7  '\bdb' => 'dv'
; 9 : "dbidal"  :::  2  'dbidal' => 'dvidal'
; 8 : "dbivAr"  :::  8  '\bdb' => 'dv'
; 8 : "dbijAy"  :::  6  '\bdb' => 'dv'
; 8 : "dbijAg"  :::  7  '\bdb' => 'dv'
; 8 : "dbijAg"  :::  1  'dbij' => 'dvij'
; 8 : "dbipaY"  :::  2  'dbipa([Yrkc])' => 'dvipa\1'
; 8 : "dbipaY"  :::  6  '\bdb' => 'dv'
; 7 : "dbiDAB"  :::  7  '\bdb' => 'dv'
; 7 : "dbisap"  :::  6  '\bdb' => 'dv'
; 7 : "dbisap"  :::  1  'dbisap' => 'dvisap'
; 7 : "dbijih"  :::  7  '\bdb' => 'dv'
; 6 : "dbAvap"  :::  5  '\bdb' => 'dv'
; 6 : "dbizaw"  :::  5  '\bdb' => 'dv'
; 6 : "dbidvA"  :::  1  '\bdb' => 'dv'
; 6 : "dbi-"  :::  1  '\bdb' => 'dv'
; 6 : "dbipal"  :::  6  '\bdb' => 'dv'
; 6 : "dbimuK"  :::  3  '\bdb' => 'dv'
; 6 : "dbimuK"  :::  2  'dbimuK' => 'dvimuK'
; 5 : "dbireP"  :::  3  '\bdb' => 'dv'
; 5 : "dbireP"  :::  2  'dbireP' => 'dvireP'
; 5 : "dbimAt"  :::  3  '\bdb' => 'dv'
; 5 : "dbimAs"  :::  5  '\bdb' => 'dv'
; 5 : "dbijay"  :::  3  'dbij' => 'dvij'
; 5 : "dbipAd"  :::  5  '\bdb' => 'dv'
; 5 : "dbipar"  :::  1  '\bdb' => 'dv'
; 4 : "dbihIn"  :::  3  '\bdb' => 'dv'
; 4 : "dbirad"  :::  4  '\bdb' => 'dv'
; 4 : "dbidoz"  :::  4  '\bdb' => 'dv'
; 4 : "dbilak"  :::  4  '\bdb' => 'dv'
; 4 : "dbibin"  :::  2  '\bdb' => 'dv'  
; 4 : "dbibin"  :::  2  'dbibin' => 'dvibin'
; 3 : "dbireK"  :::  1  '\bdb' => 'dv'
; 3 : "dbireK"  :::  2  'dbireK' => 'dvireK'
; 3 : "dbiSAl"  :::  1  '\bdb' => 'dv'
; 3 : "dbibAh"  :::  3  '\bdb' => 'dv'
; 3 : "dbiBAg"  :::  3  '\bdb' => 'dv'
; 3 : "dbiBAz"  :::  1  '\bdb' => 'dv'
; 3 : "dbiSar"  :::  2  '\bdb' => 'dv'
; 3 : "dbiKaR"  :::  3  '\bdb' => 'dv'
; 3 : "dbiniG"  :::  3  '\bdb' => 'dv'
; 3 : "dbiH"  :::  2  '\bdb' => 'dv'
; 3 : "dbimUr"  :::  3  '\bdb' => 'dv'
; 2 : "dbiDAk"  :::  2  '\bdb' => 'dv'
; 2 : "dbiSaP"  :::  2  '\bdb' => 'dv'
; 2 : "dbibah"  :::  1  '\bdb' => 'dv'
; 2 : "dbiDAr"  :::  1  '\bdb' => 'dv'
* 095 cases: (dviviDa = 'of two kinds')
; 95 : "dbiviD"  :::  90  '\bdb' => 'dv'
; 95 : "dbiviD"  :::  5  'dbiviD' => 'dviviD'
* 426 cases: (dvija = 'twice born') (dvijottama = dvija+uttama, etc.)
  'best of twice born')
   (dvijAti = 'having two births')
; 68 : "dbijaH"  :::  66  '\bdb' => 'dv'
; 68 : "dbijaH"  :::  2  'dbij' => 'dvij'
; 50 : "dbijas"  :::  47  '\bdb' => 'dv'
; 50 : "dbijas"  :::  3  'dbij' => 'dvij'
; 49 : "dbijot"  :::  46  '\bdb' => 'dv'
; 49 : "dbijot"  :::  3  'dbij' => 'dvij'
; 47 : "dbija"  :::  45  '\bdb' => 'dv'
; 47 : "dbija"  :::  2  'dbij' => 'dvij'
; 44 : "dbijAn"  :::  35  '\bdb' => 'dv'
; 44 : "dbijAn"  :::  9  'dbij' => 'dvij'
; 36 : "dbijAt"  :::  32  '\bdb' => 'dv'
; 31 : "dbijAH"  :::  27  '\bdb' => 'dv'
; 31 : "dbijAH"  :::  4  'dbij' => 'dvij'
; 19 : "dbijaS"  :::  18  '\bdb' => 'dv'
; 19 : "dbijaS"  :::  1  'dbij' => 'dvij'
; 10 : "dbijo"  :::  10  '\bdb' => 'dv'
; 9 : "dbijam"  :::  8  '\bdb' => 'dv'
; 9 : "dbijam"  :::  1  'dbij' => 'dvij'
; 7 : "dbijA"  :::  1  'dbij' => 'dvij'
; 7 : "dbijA"  :::  6  '\bdb' => 'dv'
; 7 : "dbijEH"  :::  4  '\bdb' => 'dv'
; 7 : "dbijEH"  :::  3  'dbij' => 'dvij'
; 6 : "dbijat"  :::  3  '\bdb' => 'dv'
; 6 : "dbijar"  :::  5  '\bdb' => 'dv'
; 6 : "dbijar"  :::  1  'dbij' => 'dvij'
; 6 : "dbijak"  :::  6  '\bdb' => 'dv'
; 6 : "dbijad"  :::  5  '\bdb' => 'dv'
; 6 : "dbijad"  :::  1  'dbij' => 'dvij'
; 5 : "dbijav"  :::  4  '\bdb' => 'dv'
; 5 : "dbijav"  :::  1  'dbij' => 'dvij'
; 4 : "dbijeB"  :::  4  '\bdb' => 'dv'
; 4 : "dbijA-"  :::  4  '\bdb' => 'dv'
; 4 : "dbijaB"  :::  3  '\bdb' => 'dv'
; 4 : "dbijaB"  :::  1  'dbij' => 'dvij'
; 3 : "dbijEr"  :::  2  '\bdb' => 'dv'
; 3 : "dbijEr"  :::  1  'dbij' => 'dvij'
; 3 : "dbijen"  :::  3  '\bdb' => 'dv'
; 3 : "dbijAd"  :::  2  '\bdb' => 'dv'
; 3 : "dbijAd"  :::  1  'dbij' => 'dvij'
; 3 : "dbijap"  :::  2  '\bdb' => 'dv'
; 3 : "dbijap"  :::  1  'dbij' => 'dvij'
; 3 : "dbijag"  :::  3  'dbij' => 'dvij'
(+ 66 2 47 3 46 3 45 2 35 9 32 27 4 18 1 10 8 1 1 6 4 3 3 5 1 6 5 1)
* 063 cases: (viDA = 'part'; also verb; viDAna = 'disposing')
; 51 : "dbiDA"  :::  45  '\bdb' => 'dv'
; 51 : "dbiDA"  :::  6  'dbiDA' => 'dviDA'
; 9 : "dbiDAn"  :::  9  'dbiDA' => 'dviDA'
; 3 : "dbiDAy"  :::  2  'dbiDA' => 'dviDA'
; 2 : "dbiDAH"  :::  1  'dbiDA' => 'dviDA' (viDA)
* 034 cases: (dvAtriMSat = 32)
; 34 : "dbAtri"  :::  30  '\bdb' => 'dv'
; 34 : "dbAtri"  :::  4  'dbAtri' => 'dvAtri'
* 051 cases: (vidvAn m1s of vidvas = 'one who knows', vidvadBiH)
; 29 : "dbAn"  :::  27  'vidbAn' => 'vidvAn'
; 9 : "dbadBi"  :::  9  'dbadBi' => 'dvadBi'
; 8 : "dbAMsa"  :::  8  'dbAMsa' => 'dvAMsa'
; 6 : "dbidvA"  :::  5  'dbidvA' => 'dvidvA'
; 4 : "dbAnna"  :::  3  'vidbAn' => 'vidvAn'
; 3 : "dbanma"  :::  1  'dbanm' => 'dvanm'
; 3 : "dbaddA"  :::  1  'vidbad' => 'vidvad'
; 2 : "dbatta"  :::  1  'dbat' => 'dvat' (vidvat)
* 019 cases: (vidyA = 'knowledge')
; 19 : "dbidyA"  :::  19  'dbidyA' => 'dvidyA'

* 004 cases: (vitta = 'known')
; 4 : "dbitta"  :::  4  'dbitt' => 'dvitt'
* 100 cases: (tadvAn, m1s of tadvat = 'having that')
; 29 : "dbAn"  :::  2  'dbAn(\W|$)' => 'dvAn\1'
; 57 : "dbat"  :::  57  'dbat' => 'dvat'
; 16 : "dbati"  :::  16  'dbat' => 'dvat'
; 8 : "dbadev"  :::  8  'dbadev' => 'dvadev'
; 5 : "dbacca"  :::  5  'dbac' => 'dvac'
; 4 : "dbadda"  :::  4  'tadbad' => 'tadvad'
; 3 : "dbanma"  :::  2  'dbanm' => 'dvanm'
; 3 : "dbaddA"  :::  2  'tadbad' => 'tadvad'
; 3 : "dbadDo"  :::  3  'tadbad' => 'tadvad'
; 3 : "dbadud"  :::  3  'tadbad' => 'tadvad'
; 2 : "dba-"  :::  1  'tadba-' => 'tadva-'
; 2 : "dbaccA"  :::  2  'dbac' => 'dvac'
; 2 : "dbatta"  :::  1  'dbat' => 'dvat' (tadvat)
; 2 : "dbadBa"  :::  2  'tadbad' => 'tadvad'
* 038 cases: (dvApara = '2-spot of a die', 'name of a yuga')
* 036 cases: (dvivarza = '2 years old') (dvivarRa = 'bicolor') (vivarDamAna),
  (vivaraRa = 'uncovering')
; 36 : "dbivar"  :::  32  'dbivar' => 'dvivar'
; 36 : "dbivar"  :::  4  '\bdb' => 'dv'
* 028 cases: (dvirUpa, dvirUpakoza, virUpa)
; 28 : "dbirUp"  :::  8  'dbirUp' => 'dvirUp'
; 28 : "dbirUp"  :::  20  '\bdb' => 'dv'
* 028 cases: (udvarttana = 'act of rising, etc.')
; 28 : "dbartt"  :::  28  'dbartt' => 'dvartt'
* 002 cases: (vAraRa = 'warding off')
; 2 : "dbAraR"  :::  2  'dbAraR' => 'dvAraR'
* 153 cases: (dvAr = 'door', dvAraka, dvAra)
; 21 : "dbArA"  :::  20  'dbArA\W' => 'dvArA'
; 18 : "dbAram"  :::  10  '\bdb' => 'dv'
; 18 : "dbAram"  :::  8  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
; 19 : "dbArak"  :::  3  'dbAra([^RdhB])' => 'dvAra\1'
; 19 : "dbArak"  :::  16  '\bdb' => 'dv'
; 17 : "dbAraM"  :::  4  '\bdb' => 'dv'
; 17 : "dbAraM"  :::  13  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
; 14 : "dbArap"  :::  6  'dbAra([^RdhB])' => 'dvAra\1'
; 14 : "dbArap"  :::  8  '\bdb' => 'dv'
; 14 : "dbAre"  :::  1  '\bdb' => 'dv'
; 14 : "dbAre"  :::  13  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
; 14 : "dbAri"  :::  6  '\bdb' => 'dv'
; 14 : "dbAri"  :::  3  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
; 9 : "dbAreR"  :::  9  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
; 8 : "dbArAR"  :::  7  '\bdb' => 'dv'
; 8 : "dbArAR"  :::  1  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
; 6 : "dbArav"  :::  1  'dbAra([^RdhB])' => 'dvAra\1'
; 6 : "dbArav"  :::  5  '\bdb' => 'dv'
; 5 : "dbAras"  :::  2  'dbAra([^RdhB])' => 'dvAra\1'
; 5 : "dbAras"  :::  3  '\bdb' => 'dv'
; 4 : "dbArez"  :::  1  '\bdb' => 'dv'
; 4 : "dbArez"  :::  3  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
; 3 : "dbAHsT"  :::  3  '\bdb' => 'dv'
; 3 : "dbArad"  :::  3  '\bdb' => 'dv'
; 21 : "dbArA"  :::  1  '\bdb' => 'dv'
; 2 : "dbArag"  :::  2  'dbAra([^RdhB])' => 'dvAra\1'
* 005 cases: (vAri = 'water')
; 14 : "dbAri"  :::  5  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
* 006 cases: (vara = 'enclosing, choosing')
; 3 : "dbareR"  :::  3  'dbareR' => 'dvareR'
; 3 : "dbarA"  :::  3  'saridbarA' => 'saridvarA'
* 104 cases: (dvIpa = 'island')
; 19 : "dbIpas"  :::  5  '\bdb' => 'dv'
; 19 : "dbIpas"  :::  14  'dbIp' => 'dvIp'
; 14 : "dbIpe"  :::  2  '\bdb' => 'dv'
; 14 : "dbIpe"  :::  12  'dbIp' => 'dvIp'
; 10 : "dbIpaM"  :::  3  '\bdb' => 'dv'
; 10 : "dbIpaM"  :::  7  'dbIp' => 'dvIp'
; 9 : "dbIpAn"  :::  8  'dbIp' => 'dvIp'
; 9 : "dbIpAn"  :::  1  '\bdb' => 'dv'
; 7 : "dbIpav"  :::  4  '\bdb' => 'dv'
; 7 : "dbIpav"  :::  3  'dbIp' => 'dvIp'
; 6 : "dbIpa-"  :::  5  '\bdb' => 'dv'
; 6 : "dbIpa-"  :::  1  'dbIp' => 'dvIp'
; 6 : "dbIpA"  :::  6  'dbIp' => 'dvIp'
; 5 : "dbIpAM"  :::  2  '\bdb' => 'dv'
; 5 : "dbIpAM"  :::  3  'dbIp' => 'dvIp'
; 4 : "dbIpAD"  :::  4  'dbIp' => 'dvIp'
; 4 : "dbIpan"  :::  4  'dbIp' => 'dvIp'
; 4 : "dbIpam"  :::  2  '\bdb' => 'dv'
; 4 : "dbIpam"  :::  2  'dbIp' => 'dvIp'
; 4 : "dbIpo"  :::  4  'dbIp' => 'dvIp'
; 3 : "dbIpaB"  :::  3  '\bdb' => 'dv'
; 3 : "dbIpaK"  :::  3  '\bdb' => 'dv'
; 3 : "dbIpaj"  :::  3  'dbIp' => 'dvIp'
; 3 : "dbIpap"  :::  3  'dbIp' => 'dvIp'
(+ 5 14 2 12 3 7 8 1 4 3 5 1 6 2 3 4 4 2 2 4 3 3)
* 018 cases: (udvAhatattva = Name of work)
; 18 : "dbAhat"  :::  2  '\bdb' => 'dv'
; 18 : "dbAhat"  :::  16  'dbAhat' => 'dvAhat'

* 009 cases: (dvicakra)
; 17 : "dbicakra"  :::  9  '\bdb' => 'dv'
* 008 cases: (vicakzaRa = 'conspicuous')
; 18 : "dbicak"  :::  8  'dbicakzaR' => 'dvicakzaR'
* 019 cases: (vizRu)
; 18 : "dbizRo"  :::  17  'dbizR' => 'dvizR'
; 18 : "dbizRo"  :::  1  '\bdb' => 'dv'
; 6 : "dbi-"  :::  1  'tadbi' => 'tadvi'
* 022 cases: (viSeza = 'distinction', viSizwa = 'distinguished')
; 17 : "dbiSez"  :::  1  '\bdb' => 'dv'
; 17 : "dbiSez"  :::  16  'dbiSez' => 'dviSez'
; 5 : "dbiSiz"  :::  5  'dbiSiz' => 'dviSiz'
* 018 cases: (vE = 'indeed')
; 18 : "dbE"  :::  18  'dbE(\W|$)' => 'dvE\1'
* 016 cases: (dvivacana 'the dual (gram.)')
; 16 : "dbivac"  :::  12  '\bdb' => 'dv'
; 16 : "dbivac"  :::  4  'dbivac' => 'dvivac'
* 015 cases: (dvitri '2 or 3')
; 15 : "dbitri"  :::  11  '\bdb' => 'dv'
; 15 : "dbitri"  :::  4  'dbitri' => 'dvitri'
* 020 cases: (vacana = 'speaking', etc. vaca)
; 15 : "dbacan"  :::  15  'dbacan' => 'dvacan'
; 5 : "dbacaH"  :::  5  'dbacaH' => 'dvacaH'
* 015 cases: (vahni = 'a draught animal') (udvahni = 'emitting sparks')
; 15 : "dbahni"  :::  15  'dbahni' => 'dvahni'
* 004 cases: (vah = 'to carry')
; 4 : "dbahat"  :::  4  'dbahat' => 'dvahat'
* 015 cases: (dvitaya = 'twofold')
; 15 : "dbitay"  :::  4  '\bdb' => 'dv'
; 15 : "dbitay"  :::  11  'dbitay' => 'dvitay'
* 015 cases: (vipad = 'to fall', dvipada = 'two-footed')
; 15 : "dbipad"  :::  2  'dbipad' => 'dvipad'
; 15 : "dbipad"  :::  13  '\bdb' => 'dv'
* 014 cases: (dviBuja = '2-armed')
; 14 : "dbiBuj"  :::  14  '\bdb' => 'dv'
* 013 cases: (vizaya = 'region')
; 12 : "dbizay"  :::  1  '\bdb' => 'dv'
; 12 : "dbizay"  :::  11  'dbizay' => 'dvizay'
; 6 : "dbi-"  :::  1  'tvadbi-' => 'tvadvi-'
* 060 cases: (dviza = 'hostile', vidviza, dvizat, etc.)
  (vidvizat, dvizwa, dviz,dveza)
; 10 : "dbizaH"  :::  1  '\bdb' => 'dv'
; 10 : "dbizaH"  :::  9  'dbizaH' => 'dvizaH'
; 9 : "dbizat"  :::  7  '\bdb' => 'dv'
; 7 : "dbizan"  :::  5  '\bdb' => 'dv'
; 6 : "dbizad"  :::  1  '\bdb' => 'dv'
; 6 : "dbizad"  :::  5  'dbiza([mMd])' => 'dviza\1'
; 6 : "dbizwa"  :::  1  '\bdb' => 'dv'
; 6 : "dbizwa"  :::  5  'dbizwa' => 'dvizwa'
; 6 : "dbiw"  :::  3  '\bdb' => 'dv'
; 4 : "dbizAM"  :::  2  '\bdb' => 'dv'
; 4 : "dbizAM"  :::  2  'dbizAM' => 'dvizAM'
; 4 : "dbiz"  :::  4  '\bdb' => 'dv'
; 3 : "dbezI"  :::  3  'dbez' => 'dvez'
; 3 : "dbezo"  :::  1  '\bdb' => 'dv'
; 3 : "dbezo"  :::  2  'dbez' => 'dvez'
; 3 : "dbezAd"  :::  3  'dbez' => 'dvez'
; 3 : "dbezwA"  :::  1  'dbez' => 'dvez'
; 3 : "dbezwA"  :::  2  '\bdb' => 'dv'
; 3 : "dbezwi"  :::  3  '\bdb' => 'dv'
(+ 1 9 7 5 1 5 1 5 3 2 2 4 3)
* 024 cases: (vipra = 'inspired')
; 12 : "dbiprA"  :::  12  'dbipr(A|a|e|o)' => 'dvipr\1'
; 12 : "dbipra"  :::  10  'dbipr(A|a|e|o)' => 'dvipr\1'
; 12 : "dbipra"  :::  2  '\bdb' => 'dv'
* 012 cases: (dvAviMSa = 'the 22nd', dvAviMSati = '22')
; 12 : "dbAviM"  :::  10  '\bdb' => 'dv'
; 12 : "dbAviM"  :::  2  'dbAviM' => 'dvAviM'
* 016 cases: (vizRu, vEzRava)
; 12 : "dbizRu"  :::  12  'dbizR' => 'dvizR'
; 4 : "dbEzRa"  :::  4  'dbEz' => 'dvEz'
* 012 cases: (dvEguRya = "doubling')
; 10 : "dbEguR"  :::  9  '\bdb' => 'dv'
; 10 : "dbEguR"  :::  1  'dbEguR' => 'dvEguR'
* 004 cases: (dvEviDya = 'twofold state')
; 4 : "dbEviD"  :::  4  '\bdb' => 'dv'
* 019 cases: (viza = 'poison')
; 10 : "dbizam"  :::  10  'dbiza([mMd])' => 'dviza\1'
; 9 : "dbizat"  :::  2  'dbiz' => 'dviz'
; 5 : "dbizaM"  :::  4  'dbiza([mMd])' => 'dviza\1'
; 3 : "dbizah"  :::  3  'dbiz' => 'dviz'
* 001 cases: (udvij 'to spring upwards')
; 10 : "dbijan"  :::  1  'dbij' => 'dvij' (udvij)
* 001 cases: (dvijanman = 'having a double birth')
; 10 : "dbijan"  :::  1  'dbij' => 'dvij' (dvijanman)
* 017 cases: (vinir = prefix vi + nir, viniH,vini-)
; 10 : "dbinir"  :::  10  'dbinir' => 'dvinir'
; 4 : "dbiniH"  :::  4  'dbiniH' => 'dviniH'
; 3 : "dbiniv"  :::  3  'dbiniv' => 'dviniv'
* 022 cases: (vadana,vada = 'speaking', vadanti, vAda = 'speech')
 (vad)
; 9 : "dbadan"  :::  9  'dbadan' => 'dvadan'
; 5 : "dbAda-"  :::  2  'dbAda' => 'dvAda'
; 4 : "dbadas"  :::  4  'tadbad' => 'tadvad'
; 3 : "dbivAd"  :::  3  'dbivAd' => 'dvivAd'
; 3 : "dbada"  :::  2  'tadbad' => 'tadvad'
; 3 : "dbada"  :::  1  'dbada' => 'dvada'
; 2 : "dba-"  :::  1  'tadba-' => 'tadva-'
* 007 cases: (dvitva = 'duality')
; 9 : "dbitva"  :::  7  '\bdb' => 'dv'
* 015 cases: (viDi = 'rule')
; 9 : "dbiDiv"  :::  9  'dbiDi' => 'dviDi'
; 3 : "dbiDir"  :::  3  'dbiDi' => 'dviDi'
; 3 : "dbiDin"  :::  3  'dbiDi' => 'dviDi'
* 008 cases: (vIryya=vIrya = 'manliness')
; 8 : "dbIryy"  :::  8  'dbIr' => 'dvIr'
* 025 cases: (vaktra = 'organ of speech', vaktum = 'to speak',etc.)
  ( vac = 'speak', vAcaka = 'speaking', vAc = 'speech')
; 8 : "dbaktr"  :::  8  'dbaktr' => 'dvaktr'
; 4 : "dbaktu"  :::  4  'dbaktu' => 'dvaktu'
; 4 : "dbakzy"  :::  4  'dbakzy' => 'dvakzy'
; 3 : "dbAcya"  :::  3  'dbAcya' => 'dvAcya'
; 3 : "dbAcak"  :::  3  'dbAca' => 'dvAca'
; 3 : "dbAcaM"  :::  3  'dbAca' => 'dvAca'
* 008 cases: (vastra = 'clothes')
; 8 : "dbastr"  :::  8  'dbastr' => 'dvastr'
* 005 cases: (vijan = 'to be born', udvij = )
; 8 : "dbijAy"  :::  2  'dbij' => 'dvij'
; 3 : "dbejay"  :::  3  'dbejay' => 'dvejay'
* 014 cases: (varRa = 'color')
; 8 : "dbarRa"  :::  8  'dbarR' => 'dvarR'
; 6 : "dbarRA"  :::  6  'dbarR' => 'dvarR'
* 014 cases: (svAdvI f. svAdu = 'sweet', mfdvI 'soft')
; 8 : "dbI"  :::  8  'dbI(\W|$)' => 'dvI\1'
; 6 : "dbamla"  :::  6  'svAdbamla' => 'svAdvamla'
* 005 cases: (varza = 'rain, year')
; 8 : "dbarzA"  :::  5  'dbarz' => 'dvarz' (varza)
* 007 cases: (vatsa = 'calf', vatsara = 'a year')
; 7 : "dbatsa"  :::  7  'dbat' => 'dvat'

* 007 cases: (vajra = 'hard or mighty one, thunderbolt')
; 7 : "dbajra"  :::  7  'dbajr' => 'dvajr'
* 012 cases: (vAyu = 'wind')
; 7 : "dbAyur"  :::  7  'dbAy' => 'dvAy'
; 3 : "dbAyuH"  :::  3  'dbAy' => 'dvAy'
; 2 : "dbAyO"  :::  2  'dbAy' => 'dvAy'
* 004 cases: (vidviz = 'to hate', 'hating')
; 7 : "dbizan"  :::  1  'dbizan' => 'dvizan'  (vidviz)
; 6 : "dbiw"  :::  3  'dbiw(\W)' => 'dviw\1'
* 007 cases: (vat suffix = 'likeness')
; 7 : "dbatI"  :::  7  'dbat' => 'dvat'
* 009 cases: (vimuc = 'to unloose', vimukta = 'loosened')
; 7 : "dbimuc"  :::  7  'dbimuc' => 'dvimuc'
; 2 : "dbimuk"  :::  2  'dbimuk' => 'dvimuk'
* 010 cases: (udvigna = 'shuddering')
; 7 : "dbigna"  :::  7  'dbign' => 'dvign'
; 3 : "dbignA"  :::  3  'dbign' => 'dvign'
* 003 cases: (SAdvala = 'grassy' (MW))
; 6 : "dbalAn"  :::  3  'dbal(An|aM|A\W|e|s|At|Ad|AK)' => 'dval\1' (SAdvala
* 007 cases: (vana = 'forest')
; 6 : "dbanam"  :::  4  'dbana([mMs])' => 'dvana\1' (vana)
; 4 : "dbanaM"  :::  3  'dbana([mMs])' => 'dvana\1'
* 005 cases: (vasanta = 'spring')
; 6 : "dbasan"  :::  5  'dbasan' => 'dvasan' (vasanta)
* 001 cases: (vasana = 'clothes')
; 6 : "dbasan"  :::  1  'dbasan' => 'dvasan' (vasana)
* 001 cases: (SudDi = 'cleansing')
; 6 : "dbi-"  :::  1  'Sudbi-' => 'SudDi-'
* 016 cases: (udvah = 'to carry up', udvaha)
; 6 : "dbahan"  :::  5  'dbahan' => 'dvahan'
; 5 : "dbahaH"  :::  5  'dbaha' => 'dvaha'
; 3 : "dbahet"  :::  3  'dbahet' => 'dvahet'
; 3 : "dbaha"  :::  3  'dbaha' => 'dvaha'
* 006 cases: (vAta = 'blown','wind')
; 6 : "dbAtak"  :::  6  'dbAta' => 'dvAta'
* 005 cases: (dvEta = 'duality')
; 5 : "dbEtav"  :::  5  '\bdb' => 'dv'
* 008 cases: (vaDa = 'one who kills')
; 5 : "dbaDaH"  :::  5  'dbaDa' => 'dvaDa'
; 3 : "dbaDap"  :::  3  'dbaDa' => 'dvaDa'
* 002 cases: (viBedana = 'splitting', viBeda)
; 5 : "dbiBed"  :::  1  'biBedane' => 'viBedane'
; 5 : "dbiBed"  :::  1  'tadbi' => 'tadvi'
* 002 cases: (vijaya = 'victory'
; 5 : "dbijay"  :::  2  'dbij' => 'dvij'
* 005 cases: (vastu = 'the real')
; 5 : "dbastu"  :::  5  'dbast([uv])' => 'dvast\1'
* 002 cases: (dvAja = 'son of two fathers')
; 5 : "dbAjaM"  :::  1  '\bdb' => 'dv'
; 3 : "dbAjaS"  :::  1  '\bdb' => 'dv'
* 016 cases: (vAja = 'strength', BaradvAja, BAradvAja)
; 5 : "dbAjaM"  :::  4  'dbAjaM' => 'dvAjaM'
; 3 : "dbAjo"  :::  3  'dbAj' => 'dvAj'
; 3 : "dbAjap"  :::  3  'dbAj' => 'dvAj'
; 3 : "dbAjas"  :::  3  'dbAj' => 'dvAj'
; 3 : "dbAjaS"  :::  2  'dbAj' => 'dvAj'
; 3 : "dbAjAt"  :::  3  'dbAj' => 'dvAj'
* 017 cases: (vi-pari-, vi-(root))
; 5 : "dbipar"  :::  4  'dbipa([Yrkc])' => 'dvipa\1'
; 5 : "dbAtap"  :::  5  'dbAta' => 'dvAta'
; 3 : "dbisar"  :::  3  'dbisar' => 'dvisar'
; 3 : "dbimar"  :::  3  'dbimar' => 'dvimar'
; 2 : "dbikra"  :::  2  'dbikra' => 'dvikra'
* 005 cases: (vaMSa = 'bamboo cane')
; 5 : "dbaMSa"  :::  5  'dbaMSa' => 'dvaMSa'
* 001 cases: (vihIna = 'entirely abandoned')
; 4 : "dbihIn"  :::  1  'dbihIn' => 'dvihIn'
* 004 cases: (vipula = 'large')
; 4 : "dbipul"  :::  4  'dbipul' => 'dvipul'
* 004 cases: (udvIkzya = 'having looked up', vIkzya = 'astonishing')
; 4 : "dbIkzy"  :::  4  'dbIkzy' => 'dvIkzy'
* 002 cases: (viGna = 'a breaker')
; 4 : "dbiGna"  :::  2  'dbiGn' => 'dviGn'
* 004 cases: (viSvAmitra 'friend of all, a certain sage', viSvAsa = 'confidence')
; 4 : "dbiSvA"  :::  4  'dbiSvA' => 'dviSvA'
* 004 cases: (viSva = 'all-pervading')
; 4 : "dbiSva"  :::  4  'dbiSva' => 'dviSva'
* 004 cases: (vasti = 'bladder', etc.)
; 4 : "dbasti"  :::  4  'dbasti' => 'dvasti'
* 001 cases: (vardDana (MW varDana) = 'increasing')
; 4 : "dbanaM"  :::  1  'dbana([mMs])' => 'dvana\1'
* 004 cases: (vinDya = 'N. of mountain range')
; 4 : "dbinDy"  :::  4  'dbinDy' => 'dvinDy'
* 004 cases: (varjya = 'to be excluded')
; 4 : "dbarjy"  :::  4  'dbarjy' => 'dvarjy'
* 004 cases: (vamana = 'hemp,vomiting')
; 4 : "dbaman"  :::  4  'dbaman' => 'dvaman'
* 005 cases: (mfdu = 'soft')
; 4 : "dbagni"  :::  4  'mfdbagni' => 'mfdvagni'
; 3 : "dbArip"  :::  1  'dbAr(am|aM|e|i|AR)' => 'dvAr\1'
* 003 cases: (videha = 'bodiless')
; 3 : "dbideh"  :::  3  'dbideh' => 'dvideh'
* 002 cases: (viSAla = 'spacious')
; 3 : "dbiSAl"  :::  2  'dbiSAl' => 'dviSAl'
* 005 cases: (tadvid = 'knowing that')
; 3 : "dbidaH"  :::  3  'dbidaH' => 'dvidaH'
; 2 : "dbidAm"  :::  2  'tadbi' => 'tadvi'
* 003 cases: (vAmayA = 'in a pleasant manner')
; 3 : "dbAmay"  :::  3  'dbAm' => 'dvAm'
* 006 cases: (vA = 'or', vATa = 'or else')
; 3 : "dbATa"  :::  3  'bATa ' => 'vATa '
; 3 : "dbeti"  :::  3  'dbeti' => 'dveti'
* 003 cases: (vaSya = 'to be subjected')
; 3 : "dbaSya"  :::  3  'dbaSya' => 'dvaSya'
* 003 cases: (vAsana = 'covering')
; 3 : "dbAsan"  :::  3  'dbAsa' => 'dvAsa'
* 005 cases: (dvigu = 'N. of a tatpurusha cpd.')
; 3 : "dbigus"  :::  3  '\bdb' => 'dv'
; 2 : "dbiguM"  :::  1  '\bdb' => 'dv'
; 2 : "dbiguM"  :::  1  'dbigu' => 'dvigu'
* 002 cases: (udvAsya = 'to be taken off')
; 3 : "dbAsya"  :::  2  'dbAsya' => 'dvAsya'
* 001 cases: (vicCAya = 'without shadow')
; 3 : "dbicCA"  :::  1  'dbic' => 'dvic'
* 003 cases: (vArzika = 'belonging to rainy season')
; 3 : "dbArzi"  :::  3  'dbArzi' => 'dvArzi'
* 003 cases: (vAlukI = 'sandbank, sand')
; 3 : "dbAluk"  :::  3  'dbAluk' => 'dvAluk'
* 003 cases: (vinASa = 'destruction')
; 3 : "dbinAS"  :::  3  'dbinAS' => 'dvinAS'
* 004 cases: (vEdika = 'relating to Veda', vEdya)
; 3 : "dbEdik"  :::  3  'dbEdik' => 'dvEdik'
; 3 : "dbEdya"  :::  1  'dbEdya' => 'dvEdya'
* 002 cases: (viBAzA = 'alternative')
; 3 : "dbiBAz"  :::  2  'dbiBAz' => 'dviBAz'
* 003 cases: (varAha = 'pig')
; 3 : "dbarAh"  :::  3  'dbarAh' => 'dvarAh'
* 003 cases: (vakra = 'crooked')
; 3 : "dbakrA"  :::  3  'dbakr' => 'dvakr'
* 003 cases: (vAjin = 'swift')
; 3 : "dbAjin"  :::  3  'dbAj' => 'dvAj'
* 003 cases: (vedana = 'announcing')
; 3 : "dbedan"  :::  1  '\bdb' => 'dv'
; 3 : "dbedan"  :::  2  'dbeda' => 'dveda'
* 003 cases: (viBu = 'being everywhere')
; 3 : "dbiBuH"  :::  3  'dbiBu([Hm])' => 'dviBu\1'
* 001 cases: (prasidDi = 'accomplishment')
; 3 : "dbiH"  :::  1  'prasidbiH' => 'prasidDiH'
* 002 cases: (virecana = 'opening','purging')
; 2 : "dbirec"  :::  1  'tadbi' => 'tadvi'
; 2 : "dbirec"  :::  1  'dbire' => 'dvire'
* 002 cases: (viPala = 'without fruit')
; 2 : "dbiPal"  :::  2  'dbiPal' => 'dviPal'
* 002 cases: (vikukzi = 'having a prominent belly')
; 2 : "dbikuk"  :::  2  'dbikuk' => 'dvikuk'
* 002 cases: (vihita = 'improper')
; 2 : "dbihit"  :::  2  'dbihit' => 'dvihit'
* 002 cases: (vigarhita = 'blamed')
; 2 : "dbigar"  :::  2  'dbigar' => 'dvigar'
* 002 cases: (vijYAna = 'understanding', vijYAya = 'recognizable')
; 2 : "dbijYA"  :::  2  'dbij' => 'dvij'
* 002 cases: (vEkalpika = 'optional')
; 2 : "dbEkal"  :::  2  'dbEkal' => 'dvEkal'
* 002 cases: (vidu = 'intelligent')
; 2 : "dbiduH"  :::  2  'dbidu' => 'dvidu'
* 002 cases: (viraha = 'abandonment')
; 2 : "dbirah"  :::  1  'dbirah' => 'dvirah'
; 2 : "dbirah"  :::  1  'tadbi' => 'tadvi'
* 001 cases: (vallaka = 'sea-monster')
; 2 : "dballa"  :::  1  'dballa' => 'dvalla' (vallaka)
* 001 cases: (vallaBa = 'beloved')
; 2 : "dballa"  :::  1  'dballa' => 'dvalla' (vallaBa)
* 002 cases: (udvIkzaRa = 'act of looking up')
; 2 : "dbIkza"  :::  2  'dbIkza' => 'dvIkza'
* 002 cases: (vidIrRa = 'torn')
; 2 : "dbidIr"  :::  2  'dbidIr' => 'dvidIr'
* 002 cases: (vimAna = 'aerial car')
; 2 : "dbimAn"  :::  2  'dbimAn' => 'dvimAn'
* 001 cases: (vitrAsa 'fear')
; 2 : "dbitrA"  :::  1  'dbitrA' => 'dvitrA'
* 002 cases: (vasuDA = 'producing wealth, earth')
; 2 : "dbasuD"  :::  2  'dbasu' => 'dvasu'
* 002 cases: (dvEraTa = 'chariot dual')
; 2 : "dbEraT"  :::  1  '\bdb' => 'dv'
; 2 : "dbEraT"  :::  1  'dbEr' => 'dvEr'
* 002 cases: (dvis = 'twice a day')
; 2 : "dbirdv"  :::  2  '\bdb' => 'dv'
* 002 cases: (vaSin = 'having will')
; 2 : "dbaSI"  :::  2  'dbaS' => 'dvaS'
* x cases: ()
* x cases: ()
* x cases: ()
* x cases: ()
* x cases: ()
* x cases: ()
* x cases: ()
* x cases: ()
